Pass trap continuation to prim interpreter, make call sites tail recursive
caffeinelabs/motoko pull request #2895
Opened 2021-11-11 09:56 UTC by osa1

This commit makes calls to prim interpreter (Mo_values.Prim.prim) tail
recursive by passing a "trap" continuation to it.

Previously call sites looked like this:

    try Prim.prim s env v k
    with Invalid_argument s -> trap exp.at "%s" s

This code is not tail recursive, so recursive calls to the interpreter from the
prim interpreter causes stack overflow.

With this PR we now pass a continuation for failing:

    Prim.prim { Prim.trap = trap exp.at "%s" } s env v k

The new type `trap` introduced to allow rank-2 error function. In Haskell
syntax, type of the function is

    forall a . String -> a

Without rank-2 error function, the code in prim interpreter fails to type check
as we expect the result of `trap` applications to have different types.

In the reproducer for #2844, stack overflow manifests itself as different
errors. In most cases it fails as "execution error, arithmetic overflow", but
I've also seen it fail with segfault. I don't know if this is supposed to
happen, or a bug in OCaml RTS.

Fixes #2844

2021-11-11 09:56 UTC, osa1 commented
I was looking for something simple to work on and wanted to do this (the issue is assigned to @ggreif so I asked Gabor first).

I will try to add a test. I will add an upper bound to the loop, it should loop enough to overflow the stack without this PR.

Something interesting that I discovered is, in this repro:

```
import Prim "mo:⛔";

loop {
    Prim.debugPrint(debug_show(136 : Nat32 / 32));
}
```

If I run this with `-iR` (IR interpreter), both in master and in this branch, it doesn't print anything and exits with 0. Source interpreter works fine. I think this is another bug.

2021-11-11 10:17 UTC, ggreif approved these changes
This looks really cool. The way we had to catch exceptions in the middle always irked me, and sorting to a rank-2 continuation is an elegant way of eliminating those. There are two things that surprised me
- the low number of call sites where the trap continuation needs to be passed down ( I expected a lot more)
- that rank-2 types need to be wrapped in a one-field record (would it be possible to define `type trap = 'a. string -> 'a`?

2021-11-11 10:27 UTC, osa1 commented
> that rank-2 types need to be wrapped in a one-field record (would it be possible to define type trap = 'a. string -> 'a?

As far as I understand for rank-2 polymorphism we need records or objects: https://ocaml.org/manual/polymorphism.html#s:higher-rank-poly

2021-11-11 10:32 UTC, rossberg approved these changes
Nice!

2021-11-11 10:32 UTC, rossberg commented on src/mo_values/prim.ml
> +  -> fun v -> of_big_int_trap trap t2 (as_big_int trap t1 v)
```suggestion
  | T.Nat32, T.Char ->
    fun v -> of_big_int_trap trap t2 (as_big_int trap t1 v)
```

2021-11-11 10:32 UTC, rossberg commented on src/mo_values/prim.ml
> +    trap.trap ("explicit trap: " ^ (as_text v))
```suggestion
  | "trap" -> fun _ v k -> trap.trap ("explicit trap: " ^ (as_text v))
```

2021-11-11 11:27 UTC, crusso reviewed
Nice!

Are you sure we need that rank 2 type? We don't need need it for the success continuation k (which returns unit) and I wonder if re-expressing the num_conv prims to take both a success and a trap continuation would let you avoid it.

2021-11-11 11:28 UTC, crusso commented
The ir interpreter is also written in cps and could use a similar improvement I expect...

2021-11-11 12:45 UTC, osa1 commented
Claudio points out the the `raise (Invalid_argument ...)` calls in the prim interpreter are actually for the cases where we detect a compiler (maybe type checker) bug. I think we don't want to catch those exceptions in the call sites to convert them into traps, right? We could catch them at the top level in the compiler and ask the user to report it.

If we do that then I think the prim interpreter won't need exception handling because as far as I can see all the error sites there (`raise (Invalid_argument ...)`) are for compiler bugs.

2021-12-12 12:28 UTC, nomeata commented
This has approvals. Should it be merged?

2021-12-12 21:32 UTC, ggreif requested changes
@crusso minted out that this is not optimal yet. Let's not merge at this point.

2022-01-10 17:05 UTC, nomeata commented
> @crusso pointed out that this is not optimal yet. Let's not merge at this point.

So, what’s not optimal about it? :-)

2024-01-20 20:57 UTC, closed without merging